name: Manual Approval Workflow

on:
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world"
      - uses: actions/checkout@v4

  deploy:
    needs: pre
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying to production..."

  post-deploy-approve:
    needs: deploy
    if: ${{ needs.deploy.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post Deploy Actions
        run: |
          echo "Deployment was approved. Executing post-deploy actions..."

  post-deploy-reject:
    needs: 
      - pre
      - deploy
    if: ${{ needs.pre.result == 'success' && failure() }} 
    #これがなぜか正しい
    #if: ${{ failure() }} && ${{ needs.pre.result == 'success' }}
    #if: ${{ failure() }} && ${{ needs.deploy.result == 'failure' }} && ${{ needs.pre.result == 'success' }}
    #if: ${{ needs.deploy.result == 'failure' && needs.pre.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Handle Rejection
        run: |
          echo "Deployment was rejected. Handling rejection."
